"""empty message

Revision ID: 09a6c6f1847c
Revises: 883642a723b0
Create Date: 2017-11-24 15:57:18.526056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09a6c6f1847c'
down_revision = '883642a723b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input_loose', 'act_count')
    op.drop_column('input_loose', 'loose_date')
    op.drop_column('input_loose', 'looser')
    op.drop_column('input_loose', 'materials_count')
    op.drop_column('input_loose', 'loose_time')
    op.add_column('loose_info', sa.Column('act_count', sa.Integer(), nullable=False))
    op.add_column('loose_info', sa.Column('loose_date', sa.DateTime(), nullable=True))
    op.add_column('loose_info', sa.Column('loose_time', sa.DateTime(), nullable=True))
    op.add_column('loose_info', sa.Column('looser', sa.String(length=40), nullable=False))
    op.add_column('loose_info', sa.Column('materials_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loose_info', 'materials_count')
    op.drop_column('loose_info', 'looser')
    op.drop_column('loose_info', 'loose_time')
    op.drop_column('loose_info', 'loose_date')
    op.drop_column('loose_info', 'act_count')
    op.add_column('input_loose', sa.Column('loose_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('input_loose', sa.Column('materials_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('input_loose', sa.Column('looser', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('input_loose', sa.Column('loose_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('input_loose', sa.Column('act_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
