"""empty message

Revision ID: 3986b64353ae
Revises: 09a6c6f1847c
Create Date: 2017-11-24 16:03:06.647338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3986b64353ae'
down_revision = '09a6c6f1847c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('input_loose', 'time_cut',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('loose_info', 'loose_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('loose_info', 'loose_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loose_info', 'loose_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('loose_info', 'loose_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('input_loose', 'time_cut',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
