"""empty message

Revision ID: 60f26d4545fc
Revises: 4d87b349b7de
Create Date: 2017-11-21 14:36:19.458624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f26d4545fc'
down_revision = '4d87b349b7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('input_loose', 'first_length',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('input_loose', 'second_length',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('input_loose', 'third_length',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('input_loose', 'third_length',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('input_loose', 'second_length',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('input_loose', 'first_length',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
