"""empty message

Revision ID: 883642a723b0
Revises: b97e078db5fc
Create Date: 2017-11-24 12:01:19.087344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '883642a723b0'
down_revision = 'b97e078db5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pim_defect_type', ['defect_name'])
    op.create_unique_constraint(None, 'pim_leave_type', ['leave_type'])
    op.create_unique_constraint(None, 'pim_leave_work_hand_type', ['work_hang_type'])
    op.create_unique_constraint(None, 'pim_location_type', ['position_name'])
    op.alter_column('pim_report', 'date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'pim_size', ['size_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pim_size', type_='unique')
    op.alter_column('pim_report', 'date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'pim_location_type', type_='unique')
    op.drop_constraint(None, 'pim_leave_work_hand_type', type_='unique')
    op.drop_constraint(None, 'pim_leave_type', type_='unique')
    op.drop_constraint(None, 'pim_defect_type', type_='unique')
    # ### end Alembic commands ###
