"""empty message

Revision ID: 9910ab550a67
Revises: ce9e5e46bd72
Create Date: 2017-11-23 10:56:42.931867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9910ab550a67'
down_revision = 'ce9e5e46bd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pim_leave', 'result',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pim_leave', 'result',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
