"""empty message

Revision ID: ce9e5e46bd72
Revises: 60f26d4545fc
Create Date: 2017-11-22 17:57:39.233190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9e5e46bd72'
down_revision = '60f26d4545fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pim_leave', 'num_day',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pim_leave', 'num_day',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
